---
title: "GraficoTema3"
author: "Grupo V, Tema3 : Visualización de datos"
date: "2024-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rio)
COVID<- import("data/owid-covid-data.csv")
COVID_paises_interes <- COVID[COVID$location %in% c("Spain","Italy","France","Germany","Canada","Japan","United States","United Kingdom"),]

library(tidyverse)
capa_base <- ggplot(COVID_paises_interes, aes(x = date, y = new_deaths_smoothed_per_million, color = location, size = location)) +
  geom_line(linetype = "solid")

capa_base
#Capa en la que se definen las variables correspondientes los ejes junto las del color y el tamaño de las letras correctamente, el size se usará para poder modificar el de España posteriormente

titulos <- capa_base +
  labs(title = "Daily new confirmed COVID-19 deaths per million people",
       subtitle = "7-day rolling average. For some countries the number of confirmed deaths. This is because of limited\n testing and challenges in the attribution of the cause of death.",
       x = "",
       y = "",
       caption = "Source: Our World in Data: Coronavirus Pandemic (COVID-19)")

titulos
#Se definen el título, subtítulo y pie de gráfico, se eliminan los labs en x e y a parte.

color_especifico <- titulos +
  scale_color_manual(values = c("Spain" = "red", "United States" = "purple", "United Kingdom" = "pink", "Japan" = "darkgrey", "Canada" = "brown", "France" = "orange", "Germany" = "darkgreen", "Italy" = "lightblue"))

color_especifico
#Se ponen los colores correctos a cada pais que se quiere representar.

grosor_linea <- color_especifico +
  scale_size_manual(values = c("Spain" = 0.9, "United States" = 0.5, "United Kingdom" = 0.5, "Japan" = 0.5, "Canada" = 0.5, "France" = 0.5, "Germany" = 0.5, "Italy" = 0.5))

grosor_linea
#Se definen los grosores de cada linea, España más gruesa

limites_intervalos <- grosor_linea +
  scale_y_continuous(breaks = seq(0, 18, 2)) +
  scale_x_date(date_breaks = "8 months", date_labels = "%b%d,%Y", limits = c(min(COVID_paises_interes$date), max(COVID_paises_interes$date)))

limites_intervalos
#se establecen los limites e intervalos del eje x e y.

temas_y_background <- limites_intervalos +
  theme_classic() +
  theme(panel.grid.major.y = element_line(colour = "black", linetype = "dashed"), panel.grid.minor = element_blank(),plot.caption.position = "plot",
        plot.title = element_text(color = "gray35", size = 17, family ="serif"),
        plot.subtitle = element_text(color = "gray45", size = 12, family = "serif"),
        plot.caption = element_text(color = "gray45 ", size = 12, family = "serif",hjust = 0))

#Finalmente se establece el theme classic para obtener el fondo de grafico requerido, se pone en blanco y las lineas correspondientes a los valores del eje y se ponen a rayas, para acabar se establece el tamaño, color y tipo de fuente buscado de cada parte de texto en el gráfico, el plot se pone en el lado izquierdo.
#serif = Times New Roman
final <- temas_y_background

final

library(plotly)
ggplotly(final)

ggsave(final, file = "GraficoTema3.pdf")

```

